async function run() {}

run().catch(console.error)
